### ISSUE TITLE
Node 4.1 support

### ISSUE THREAD

**Issue by alanhogan** [sass-eyeglass/eyeglass-spriting#12]
It looks like this is incompatible with node 4.1.0 at this time.

This isn’t of concern to me at this time, but thought there should probably be an issue to discuss / track support.

**Comment by alanhogan** [comment]
(Seems like a lot of folks are having node-gyp problems in node 4.1. My current approach is sitting tight on 0.12 for the time being. Gotta say, the current major version of node jumping from 0 to 4 nearly overnight has confused a lot of people around me)

**Comment by chriseppstein** [comment]
I bumped into this recently :( will dig in for next release.

**Comment by eoneill** [comment]
See https://github.com/nodejs/node/issues/2798

Workaround is to use `g++ >= 4.8`

**Comment by alanhogan** [comment]
Super long discussion there! I see only passing reference to g++ in it. Is eyeglass-spriting confirmed to work in node 4.x and newer?

**Comment by eoneill** [comment]
Yep, confirmed `eyeglass-spriting` works in node 4+. I'm using it locally with node 5 and all tests are passing in travis now in 4+.

This was the change needed to get it passing in travis: https://github.com/eoneill/eyeglass-spriting/commit/f2fc3ad672c970d25a04b9642d005f585d061694

**Comment by alanhogan** [comment]
Ah, thanks. That will be helpful.
