### ISSUE TITLE
Don’t require users to `@import "assets"`

### ISSUE THREAD

**Issue by alanhogan** [sass-eyeglass/eyeglass-spriting#9]
Would it be feasible to allow users to simply `@import "spriting"` without also necessitating `@import "assets"`? Since assets seems to be a dependency of spriting, maybe it should just import it internally.

**Comment by chriseppstein** [comment]
`@import "assets"` imports assets imports the app's assets. But there are other use cases, for instance maybe you just want one plugin's assets. I don't think it's a good assumption for spriting to know which assets to import.
